import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans, Poppins } from "next/font/google";
import "./globals.css";

import Header from "@components/templates/Header";
import Footer from "@components/templates/Footer";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: ["100","200","300","400","500","600","700","800","900"], subsets: ["latin"] });
const jkt = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
